In [1]:
# 0 D array
import numpy as np
a=np.array(45)
print(a)

45


In [5]:
# 1 D array
b=np.array([1,2,3])
print(b)

[1 2 3]


In [9]:
# 2 D array
c=np.array([[1,2],[3,4],[5,6]])
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
# 3 D array
d=np.array([[[2,4,5],[3,2,1]]])
print(d)

[[[2 4 5]
  [3 2 1]]]


In [25]:
# higher dimensional array
e=np.array([1,2,3],ndmin=5)
print(e)
print(e.ndim,"dimension array")

[[[[[1 2 3]]]]]
5 dimension array


In [29]:
# access array elements in 1D array
f=np.array([1,2,3])
print(f[0])

1


In [31]:
# access array elements in 2D array
g=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(g[2,1])

8


In [47]:
# access array elements in 3D array
h=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(h[0,2,1])
print(h.ndim)

8
3


In [61]:
# access array elements in 3D array
h=np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[1,2,3]
    ]
])
print(h[1,1,1])
print(h.ndim)

2
3


In [67]:
# negative indexing
h=np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [7,8,9],[1,2,3]
    ]
])
print(h[1,1,-3])

1


In [11]:
# array slicing
a=np.array([1,2,3,4,5])
print(a[1:5])

[2 3 4 5]


In [13]:
# array slicing with step by 2
a=np.array([1,2,3,4,5])
print(a[1:5:2])

[2 4]


In [35]:
# revere array
a=np.array([1,2,3,4,5])
print(a[::-1])

[1 3 5]


In [41]:
# slicing another way
a=np.array([[1,2,3,4,5],[2,31,4,5,4]])
print(a[1,1:3])

[31  4]


In [45]:
# slicing another way
a=np.array([[1,2,3,4,5],[2,31,4,5,4]])
print(a[1:3,2])

[4]


In [39]:
# slicing another way
a=np.array([[1,2,3,114,5],[2,31,41,15,4]])
print(a[::2])

[[  1   2   3 114   5]]


In [47]:
a=np.array([[1,2,3,114,5],[2,31,41,15,4]])
print(a[0:2,1:4])

[[  2   3 114]
 [ 31  41  15]]


In [55]:
a=np.array([1,3,5,3])
print(a.dtype)
b=np.array(['apple','banana'])
print(b.dtype)# unicode string
c=np.array([1.2,4.3])
print(c.dtype)

int32
<U6
float64


In [71]:
# convert dataype
c=np.array([1.2,4.3])
print(c.dtype)
# integer
d=c.astype('i')
print(d.dtype)
# string
d=c.astype('S')
print(d.dtype)
# boolean
d=c.astype('bool')
print(d.dtype)
# comples
d=c.astype('c')
print(d.dtype)
# time delta
d=c.astype('m')
print(d.dtype)
# unicode
d=c.astype('U')
print(d.dtype)


float64
int32
|S32
bool
|S1
timedelta64
<U32


In [75]:
# copy array
a=np.array([1,2,3])
b=a.copy()
print(b)

[1 2 3]


In [77]:
a=np.array([1,2,3])
b=a.view()
print(b)

[1 2 3]


In [80]:
a=np.array([1,2,3])
a[0]=100
print(a)

[100   2   3]


In [88]:
a=np.array([1,2,3])
b=a.view()
a[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [93]:
a=np.array([1,2,3])
b=a.copy()
a[0]=100
print(a)
print(b)

[100   2   3]
[1 2 3]


In [107]:
a=np.array([[1,2,3],[3,4,5]])
# to find order of array
print(a.shape)
# to change order of array
b=a.reshape(3,2)
print(b)

(2, 3)
[[1 2]
 [3 3]
 [4 5]]


In [129]:
a=np.array([1,2,3,4,5,6,7,8,9,12])
print(a)
b=a.reshape(5,2,1)
print(b)

[ 1  2  3  4  5  6  7  8  9 12]
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [12]]]


In [131]:
a=np.array([1,2,3,4,5,6,7,8,9,12])
print(a)
b=a.reshape(5,2,-1)
print(b)

[ 1  2  3  4  5  6  7  8  9 12]
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [12]]]


In [139]:
a=np.array([[1,2,3,4,5],[6,7,8,9,12]])
print(a)
b=a.reshape(-1)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 12]]
[ 1  2  3  4  5  6  7  8  9 12]


In [143]:
a=np.array([1,2,3,4,5])
for i in a:
    print(i)

1
2
3
4
5


In [147]:
a=np.array([[1,2,3,4,5],[6,7,8,9,12]])
for i in a:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 12]


In [153]:
a=np.array([[1,2,3,4,5],[6,7,8,9,12]])
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
12


In [159]:
a=np.array([[1,2,3,4,5],[6,7,8,9,12]])
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
12


In [47]:
# find dimension and datatype of array
import numpy as np
a=np.array([[1,2,3],[11,22,33]])
print(a)
print("Dimension:",a.ndim)
print("Datatype:",a.dtype)
print("-------------------------")
# change 2D into 3D array
b=a.reshape(1,2,3)
print(b)
print("Datatype:",b.ndim)
# change datatype
c = b.astype(float)
print("Array with changed datatype:")
print(c)
print("Datatype:", c.dtype)

[[ 1  2  3]
 [11 22 33]]
Dimension: 2
Datatype: int32
-------------------------
[[[ 1  2  3]
  [11 22 33]]]
Datatype: 3
Array with changed datatype:
[[[ 1.  2.  3.]
  [11. 22. 33.]]]
Datatype: float64


In [56]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
# nditer :  iterator to go through the array

# flags=['buffered'] :allows the iterator to access elements in a buffered way, 
# which can improve performance when processing larger arrays

# buffering helps speed up the processing of data by minimizing direct memory access 
# and optimizing how data is handled during iteration.

# op_dtypes='S'  tells it to convert the numbers into byte strings

for i in np.nditer(a,flags=['buffered'],op_dtypes='S'):
    print(i)

[[1 2 3]
 [4 5 6]]
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [70]:
# track of the indices of each element
a=np.array([1,2,3])
for i,j in np.ndenumerate(a):
    print(i,j)
print("_----------------_")
a=np.array([[1,2,3],[4,5,6]])
for i,j in np.ndenumerate(a):
    print(i,j)
print("_----------------_")
a=np.array([[[1,2,3],[4,5,6],[42,51,61]]])
for i,j in np.ndenumerate(a):
    print(i,j)

(0,) 1
(1,) 2
(2,) 3
_----------------_
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
_----------------_
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 42
(0, 2, 1) 51
(0, 2, 2) 61


In [106]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
ab=np.concatenate((a,b))
print(ab)

[[5 6]
 [7 8]
 [1 2]
 [3 4]]


In [102]:

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stack along the  axis 
stacked = np.stack((b,a),axis=0)
print(stacked)
print("-----------------")
stacked = np.stack((b,a),axis=1)
print(stacked)

[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]
-----------------
[[[5 6]
  [1 2]]

 [[7 8]
  [3 4]]]


In [110]:

a = np.array([1,2,3])
b = np.array([4,5,6])

# Stack along the  axis 
stacked = np.stack((b,a),axis=0)
print(stacked)
print("-----------------")
stacked = np.stack((b,a),axis=1)
print(stacked)

[[4 5 6]
 [1 2 3]]
-----------------
[[4 1]
 [5 2]
 [6 3]]


In [114]:
a = np.array([1,2,3])
b = np.array([4,5,6])
ab=np.hstack((a,b))
print(ab)

[1 2 3 4 5 6]


In [126]:
a = np.array([1,2,3])
b = np.array([4,5,6])
ab=np.vstack((a,b))
print(ab)

[[1 2 3]
 [4 5 6]]


In [128]:
a = np.array([1,2,3])
b = np.array([4,5,6])
ab=np.dstack((a,b))
print(ab)

[[[1 4]
  [2 5]
  [3 6]]]


In [132]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Concatenate
concat_result = np.concatenate((a, b))
print("Concatenate:", concat_result)
# Horizontal Stack
hstack_result = np.hstack((a, b))
print("Horizontal Stack:", hstack_result)
# Vertical Stack
vstack_result = np.vstack((a, b))
print("Vertical Stack:\n", vstack_result)
# Depth Stack
dstack_result = np.dstack((a, b))
print("Depth Stack:\n", dstack_result)
# Stack
stack_result_axis0 = np.stack((a, b), axis=0)  # Shape (2, 3)
print("Stack (axis=0):\n", stack_result_axis0)
stack_result_axis1 = np.stack((a, b), axis=1)  # Shape (3, 2)
print("Stack (axis=1):\n", stack_result_axis1)


Concatenate: [1 2 3 4 5 6]
Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Depth Stack:
 [[[1 4]
  [2 5]
  [3 6]]]
Stack (axis=0):
 [[1 2 3]
 [4 5 6]]
Stack (axis=1):
 [[1 4]
 [2 5]
 [3 6]]


In [150]:
a=np.array([1,2,3,4,5,6])
# split the array a into smaller sub-arrays
b=np.array_split(a,3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [170]:
a=np.array([[1,2,3,4,5,6],[11,223,43,14,35,16]])
# Split the array a into 3 parts along the second axis (columns)
b = np.array_split(a,3, axis=1)
print(b)

[array([[  1,   2],
       [ 11, 223]]), array([[ 3,  4],
       [43, 14]]), array([[ 5,  6],
       [35, 16]])]


In [194]:
a = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])
b=np.array_split(a,2,axis=1)
print(b)

[array([[[ 1,  2,  3]],

       [[ 7,  8,  9]],

       [[13, 14, 15]]]), array([[[ 4,  5,  6]],

       [[10, 11, 12]],

       [[16, 17, 18]]])]


In [208]:
a=np.array([[1,2,3],[11,223,16],[211,2223,243]])
# Split the array a into 3 parts horizontaly
b = np.hsplit(a,3)
print(b)

[array([[  1],
       [ 11],
       [211]]), array([[   2],
       [ 223],
       [2223]]), array([[  3],
       [ 16],
       [243]])]


In [243]:
a=np.array([1,2,3,4,51,22,4,55,9])
print(np.sort(a))

[ 1  2  3  4  4  9 22 51 55]


In [216]:
a = np.array([
    [[1, 21, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])
print(np.sort(a))

[[[ 1  3 21]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [228]:
a=np.array([[1,2,3],[11,223,16],[222211,22223,243]])
print(np.sort(a))

[[     1      2      3]
 [    11     16    223]
 [   243  22223 222211]]


In [224]:
a=np.array(['banana','apple','grapers'])
print(np.sort(a))

['apple' 'banana' 'grapers']


In [232]:
a=np.array([True,False,True])
print(np.sort(a))

[False  True  True]


In [249]:
# returns the indices that would sort an array
a=np.array([1,2,3,4,51,22,4,55,9])
print(np.argsort(a))

[0 1 2 3 6 8 5 4 7]


In [253]:
# flip array 
a=np.array([1,2,3,4,51,22,4,55,9])
print(np.flip(a))

[ 9 55  4 22 51  4  3  2  1]


In [257]:
a=np.array([1,2,3,4])
x=np.array([True,False,False,True])
b=a[x]
print(b)

[1 4]


In [24]:
# zeros matrix
a=np.zeros((2))
print(a)
print(a.ndim)

[0. 0.]
1


In [16]:
# zeros matrix
a=np.zeros((2,2))
print(a)
print(a.ndim)

[[0. 0.]
 [0. 0.]]
2


In [22]:
# zeros matrix
a=np.zeros((2,2,2))
print(a)
print(a.ndim)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3


In [30]:
# arange()
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [40]:
# full matrix
# Create a 1D array of length 5 filled with the value 10
a_1d = np.full(5, 10)
print("1D Array:")
print(a_1d)


# Create a 2D array with shape (2, 3) filled with the value 10
a=np.full((2,3),10)
print("\n2D Array:")
print(a)


# Create a 3D array with shape (2, 3, 4) filled with the value 10
a_3d = np.full((2, 3, 4), 10)
print("\n3D Array:")
print(a_3d)

1D Array:
[10 10 10 10 10]

2D Array:
[[10 10 10]
 [10 10 10]]

3D Array:
[[[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]]


In [46]:
a=np.linspace(2,8,4)
print(a)

[2. 4. 6. 8.]


In [48]:
a=np.random.random(5)
print(a)

[0.83943689 0.5027047  0.08766401 0.03482255 0.91464569]


In [62]:
a=np.random.randint(5)
print(a)
a=np.random.randint(3,5)
print(a)
a=np.random.randint(5,8,10)
print(a)
a=np.random.randint(5,size=(100))
print(a)

2
4
[6 5 5 7 7 5 7 5 6 6]
[1 0 1 1 3 4 3 4 2 4 1 0 3 3 4 4 1 3 0 2 3 3 4 1 0 2 0 0 2 1 0 0 0 2 1 0 3
 4 3 1 0 0 2 2 4 4 1 0 3 4 0 4 4 1 4 2 0 3 4 3 1 2 2 4 3 1 2 3 2 2 3 4 0 3
 2 2 1 3 4 4 4 4 1 0 0 2 2 0 1 2 4 1 3 4 0 4 3 2 1 1]


In [70]:
import numpy.random as r
a=r.randint(5,size=(100))
print(a)

[2 0 2 4 3 2 3 4 2 0 4 0 1 4 0 2 1 4 0 1 4 3 1 3 1 0 0 0 3 3 1 0 0 4 4 1 3
 0 2 3 1 2 3 2 2 2 2 2 1 1 4 1 0 2 1 0 0 3 0 3 3 4 4 3 4 3 3 1 0 2 3 2 2 0
 0 1 3 3 1 3 4 4 0 2 4 2 1 2 4 3 3 1 0 2 2 4 3 2 1 4]


In [68]:
from numpy import random
a=random.randint(5,size=(100))
print(a)

[4 4 3 1 0 1 3 4 0 3 2 1 3 2 1 3 3 3 2 1 1 4 0 4 4 3 2 2 2 3 3 0 4 1 1 3 4
 1 2 3 0 3 4 1 1 2 2 3 2 1 2 4 0 2 0 2 4 1 3 0 2 1 1 3 0 0 3 3 2 0 4 2 2 0
 3 2 0 2 1 2 1 1 4 2 1 2 2 0 4 0 2 0 2 2 0 2 4 4 2 2]


In [79]:
import numpy.random as r

# Create a 2D array of random integers between 2 and 10 with shape (2, 2)
a = r.randint(2, 10, (2, 2))
print(a)
print("Number of dimensions:", a.ndim)
# Create a 1D array of random integers between 2 and 10 with length 5
a_1d = r.randint(2, 10, 5)
print("1D Array:")
print(a_1d)
print("Number of dimensions:", a_1d.ndim)
# Create a 3D array of random integers between 2 and 10 with shape (2, 3, 4)
a_3d = r.randint(2, 10, (2, 3, 4))
print("\n3D Array:")
print(a_3d)
print("Number of dimensions:", a_3d.ndim)


[[9 6]
 [7 7]]
Number of dimensions: 2
1D Array:
[7 5 8 8 5]
Number of dimensions: 1

3D Array:
[[[7 8 3 4]
  [6 8 7 2]
  [3 7 9 2]]

 [[6 6 7 2]
  [3 2 7 2]
  [6 4 6 7]]]
Number of dimensions: 3


In [89]:
# find order of array
import numpy as np
a = np.array([[6, 6, 7, 2],
              [3, 2, 7, 2],
              [6, 4, 6, 7]])
print(a.shape)

(3, 4)


In [95]:
print(a.size)
print(a.itemsize)
print(a.ndim)
print(a.nbytes)

12
4
2
48


In [103]:
# np.append() adds elements to the end of the array.
# np.insert() adds elements at a specified index, and it does not require the axis parameter for 1D arrays.
a=np.array([1,2,34,2])
b=np.append(a,44)
print(b)
c=np.insert(a,1,22,axis=0)
print(c)

[ 1  2 34  2 44]
[ 1 22  2 34  2]


In [109]:
# Step 1: Create the original 2D array
a = np.array([[1, 2], [34, 2]])
print("Original 2D Array:")
print(a)
# Step 2: Append a new row
b = np.append(a, [[44, 45]], axis=0)
print("\nAfter Appending Row:")
print(b)
# Step 3: Append a new column
c = np.append(a, [[5], [6]], axis=1)
print("\nAfter Appending Column:")
print(c)
# Step 4: Insert a new row at index 1
d = np.insert(a, 1, [[99, 99]], axis=0)
print("\nAfter Inserting Row:")
print(d)
# Step 5: Insert a new column at index 1
e = np.insert(a, 1, [100, 200], axis=1)
print("\nAfter Inserting Column:")
print(e)

Original 2D Array:
[[ 1  2]
 [34  2]]

After Appending Row:
[[ 1  2]
 [34  2]
 [44 45]]

After Appending Column:
[[ 1  2  5]
 [34  2  6]]

After Inserting Row:
[[ 1  2]
 [99 99]
 [34  2]]

After Inserting Column:
[[  1 100   2]
 [ 34 200   2]]


In [134]:
a = np.array([[1, 2], [34, 2]])
b=np.delete(a,1,axis=1)
print(b)
print(b.ndim)


[[ 1]
 [34]]
2


In [123]:
a=np.array([1,2,3])
print(a)
b=np.append(a,"hi")
print(b)
# c=np.insert(a,1,"hi")
# print(c)

[1 2 3]
['1' '2' '3' 'hi']


In [153]:
a = np.array([1, 2, 3, 4, 5, 6])
# Find the index of the value 4
x = np.where(a == 4)
print("Index of value 4:", x)
# Delete the element at the found index
b = np.delete(a, x[0])
print("Array after deleting the value:")
print(b)

Index of value 4: (array([3], dtype=int64),)
Array after deleting the value:
[1 2 3 5 6]


In [155]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.delete(a, np.where(a==4))
print("Array after deleting the value:")
print(b)

Array after deleting the value:
[1 2 3 5 6]


In [169]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
np.split(a, 3, axis=0)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [171]:
np.split(a, 3, axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [173]:
np.array_split(a,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [187]:
a=np.array([1,2,3,4,5,6,7,8])
x=np.array_split(a,3)
print(x)
y=np.split(a,2)
print(y)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [201]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b= np.split(a, [1, 2]) 
print(b)
c=np.array_split(a, [1, 5]) 
print(c)
d= np.split(a, [2, 5])
print(d)

[array([1]), array([2]), array([3, 4, 5, 6, 7])]
[array([1]), array([2, 3, 4, 5]), array([6, 7])]
[array([1, 2]), array([3, 4, 5]), array([6, 7])]


In [209]:
# element operation
a = np.array([1, 2, 3, 4, 5])
add = a + 5  
print(add)
sub= a - 2  
print(sub)
mul = a * 3 
print(mul)
div = a / 2  
print(div)
sq = a**2
print(sq)
b=np.array([2,3,4,5,6])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a**b)

[ 6  7  8  9 10]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[ 3  5  7  9 11]
[-1 -1 -1 -1 -1]
[0.5        0.66666667 0.75       0.8        0.83333333]
[ 2  6 12 20 30]
[    1     8    81  1024 15625]


In [221]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.subtract(b,a)
print(c)
d=np.add(b,a)
print(d)
e=np.multiply(b,a)
print(e)
f=np.divide(b,a)
print(f)
g=np.sqrt(a)
print(g)

[3 3 3]
[5 7 9]
[ 4 10 18]
[4.  2.5 2. ]
[1.         1.41421356 1.73205081]


In [227]:
a=np.sin(0)
print(a)
b=np.cos(1)
print(b)
c=np.tan(1)
print(c)
d=np.log(10)
print(d)
e=np.log10(1)
print(e)
f=np.exp(5)
print(f)

0.0
0.5403023058681398
1.5574077246549023
2.302585092994046
0.0
148.4131591025766


In [232]:
a=np.array([1,2,3])
b=np.std(a)
print(b)

0.816496580927726


In [14]:
# Convert an Array to Float Type
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Convert to float type
float_arr = arr.astype(float)
print("Converted to float type:", float_arr)


Converted to float type: [1. 2. 3. 4. 5.]


In [18]:
# Create an 8x8 Checkerboard Pattern
import numpy as np

# Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)


8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
# Convert Centigrade to Fahrenheit
import numpy as np

# Centigrade values
centigrade = np.array([0, 20, 30, 100])
# Convert to Fahrenheit
fahrenheit = (centigrade * 9/5) + 32
print("Centigrade to Fahrenheit:\n", fahrenheit)


Centigrade to Fahrenheit:
 [ 32.  68.  86. 212.]


In [22]:
# Find the Number of Elements, Length of One Element, and Total Bytes Consumed
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])
# Number of elements
num_elements = arr.size
# Length of one element in bytes
element_size = arr.itemsize
# Total bytes consumed
total_bytes = arr.nbytes

print("Number of elements:", num_elements)
print("Length of one element in bytes:", element_size)
print("Total bytes consumed by the elements:", total_bytes)


Number of elements: 5
Length of one element in bytes: 4
Total bytes consumed by the elements: 20


In [24]:
# Test Whether Each Element of a 1-D Array is Present in a Second Array
import numpy as np

# Define two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
# Test membership
membership = np.isin(arr1, arr2)
print("Elements of arr1 present in arr2:", membership)


Elements of arr1 present in arr2: [False False  True  True  True]


In [26]:
# Find Common Values Between Two Arrays
import numpy as np

# Define two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])
# Find common values
common_values = np.intersect1d(arr1, arr2)
print("Common values between arr1 and arr2:", common_values)


Common values between arr1 and arr2: [4 5]


In [164]:
#  Remove Specific Elements from an Array
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# Indices to delete: 0 (first), 3 (fourth), and 4 (fifth)
indices_to_delete = [0, 3, 4]

# Create a new array without the specified elements
new_arr = np.delete(arr, indices_to_delete)
print("After removing specific elements:", new_arr)


After removing specific elements: [ 20  30  60  70  80  90 100]


In [166]:
# Replace Negative Values with 0
# Original array
arr = np.array([-1, -4, 0, 2, 3, 4, 5, -6])

# Replace negative values with 0
arr[arr < 0] = 0
print("After replacing negatives with 0:", arr)


After replacing negatives with 0: [0 0 0 2 3 4 5 0]


In [168]:
# Create an Array of 10 Zeros, 10 Ones, and 10 Fives
# Create arrays
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)

# Concatenate the arrays
combined = np.concatenate((zeros, ones, fives))
print("Array of 10 zeros, 10 ones, and 10 fives:", combined)


Array of 10 zeros, 10 ones, and 10 fives: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [170]:
# Create an Array of Integers from 30 to 70
# Create an array of integers from 30 to 70
arr = np.arange(30, 71)
print("Array of integers from 30 to 70:", arr)


Array of integers from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [172]:
# Create an array of even integers from 30 to 70
even_arr = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:", even_arr)


Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [174]:
# Generate a random number between 0 and 1
random_number = np.random.rand()
print("Random number between 0 and 1:", random_number)


Random number between 0 and 1: 0.6465764597884672


In [176]:
# Create a 3x3 matrix with values from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values from 2 to 10:\n", matrix)


3x3 matrix with values from 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [178]:
# Original array
arr = np.arange(12, 38)  # Equivalent to [12, 13, ..., 37]
print("Original array:", arr)

# Reverse the array
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [180]:
# Original array
original_arr = np.array([10, 20, 30])
values_to_append = [40, 50, 60, 70, 80, 90]

# Append values
appended_arr = np.append(original_arr, values_to_append)
print("After appending values:", appended_arr)


After appending values: [10 20 30 40 50 60 70 80 90]


In [182]:
# Define the two arrays
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

# Find the union
union_array = np.union1d(array1, array2)
print("Unique sorted array of values in either array:", union_array)


Unique sorted array of values in either array: [ 0 10 20 30 40 50 60 70 80]


In [3]:
import numpy as np
a=np.ones(4)
print(a)

[1. 1. 1. 1.]


In [8]:
a=np.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a=np.array([[1,2,3],[4,6,5]])
b=np.ravel(a)
print(b)

[1 2 3 4 6 5]


In [46]:
import numpy as np
a= np.array([3.7, -3.7, 2.7, 3.5, -3.5,1.5,1.6])
f = np.floor(a)
c = np.ceil(a)
r = np.round(a)
print("Original:", a)
print("Floored:", f)
print("Ceiled:", c)
print("Rounded:", r)

y=np.min(a)
print(y)

y=np.max(a)
print(y)

Original: [ 3.7 -3.7  2.7  3.5 -3.5  1.5  1.6]
Floored: [ 3. -4.  2.  3. -4.  1.  1.]
Ceiled: [ 4. -3.  3.  4. -3.  2.  2.]
Rounded: [ 4. -4.  3.  4. -4.  2.  2.]
-3.7
3.7


In [48]:
a=np.array([5.5,2.5,3.5,4.5])
f = np.floor(a)
c = np.ceil(a)
r = np.round(a)
print("Original:", a)
print("Floored:", f)
print("Ceiled:", c)
print("Rounded:", r)

Original: [5.5 2.5 3.5 4.5]
Floored: [5. 2. 3. 4.]
Ceiled: [6. 3. 4. 5.]
Rounded: [6. 2. 4. 4.]


In [64]:
a=np.ones((2,3))
b=np.full((3,2),5)
print(a)
print(b)
print("----------")
out=np.matmul(a,b)
print(out)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
----------
[[15. 15.]
 [15. 15.]]


In [82]:
a=np.array([[1, 2],[3, 4]])
# Attempt to calculate the determinant
det_a = np.linalg.det(a)
print("\nDeterminant of Matrix a:")
print(det_a)



Determinant of Matrix a:
-2.0000000000000004


In [97]:
data=np.genfromtxt('abc.txt',delimiter=',')
new_data=data.astype('int32')
print(new_data)

[2 3 4 5 6 7 7 6 1]


In [109]:
print(new_data>5)
print(new_data>=5)
print(new_data<5)
print(new_data<=5)
print(new_data==5)

[False False False False  True  True  True  True False]
[False False False  True  True  True  True  True False]
[ True  True  True False False False False False  True]
[ True  True  True  True False False False False  True]
[False False False  True False False False False False]


In [115]:
a=np.array([[1,2,3],[4,5,6]])
np.all(a>5,axis=1)

array([False, False])

In [117]:
a=np.array([[1,2,3],[4,5,6]])
np.all(a>5,axis=0)

array([False, False, False])

In [123]:
a=np.array([[1,2,3],[4,5,6]])
a[a>5]

array([6])

In [133]:
a=np.array([[1,2,3],[4,5,6]])
a[((a<5) & (a>3))]

array([4])

In [135]:
a=np.array([[1,2,3],[4,5,6]])
a[a%2==0]

array([2, 4, 6])

In [139]:
a=np.array([1,2,3])
b=np.array([2,4,3])
np.equal(a,b)

array([False, False,  True])

In [141]:
a=np.array([1,2,3])
b=np.array([2,4,3])
np.array_equal(a,b)

False

In [184]:
# Create a 2D array
x = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 1D array
y = np.array([10, 20, 30])

# Broadcasting happens here with addition
result = np.add(x, y)  # y is broadcasted to each row of x
print(result)

# Sum the resulting array
sum_result = np.sum(result)
print("Sum of all elements:", sum_result)


[[11 22 33]
 [14 25 36]]
Sum of all elements: 141


In [189]:
x = np.array([[1, 2, 3],[4, 5, 6]])

y = np.array([10, 20, 30])
result = np.add(x, y)  
print(result)

sum_result = np.sum(result)
print("Sum of all elements:", sum_result)


[[11 22 33]
 [14 25 36]]
Sum of all elements: 141
